# Generated by Django 5.1.2 on 2024-10-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_church_options_alter_missionary_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='location',
            new_name='church_address',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='phone_number',
            new_name='church_number',
        ),
    ]
