# Generated by Django 4.2.16 on 2025-02-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='BaseApp.tag'),
        ),
        migrations.DeleteModel(
            name='TagRecord',
        ),
    ]
