# Generated by Django 5.1.2 on 2024-10-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name_plural': 'Churches'},
        ),
        migrations.AlterModelOptions(
            name='missionary',
            options={'verbose_name_plural': 'Missionaries'},
        ),
    ]
