# Generated by Django 5.1.2 on 2024-10-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_location_church_church_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='pastor_name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
