# Generated by Django 5.1.2 on 2024-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_church_pastor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionary',
            name='field_of_service',
            field=models.CharField(default='Africa', max_length=100),
        ),
        migrations.AlterField(
            model_name='church',
            name='pastor_name',
            field=models.CharField(max_length=100),
        ),
    ]
