# Generated by Django 4.2.16 on 2024-11-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalmedia',
            options={'verbose_name_plural': 'External Media'},
        ),
        migrations.AlterModelOptions(
            name='missionary',
            options={'verbose_name_plural': 'Missionaries'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name_plural': 'Search History'},
        ),
        migrations.AlterModelOptions(
            name='tagrecord',
            options={'verbose_name_plural': 'Tag Records'},
        ),
    ]
