# Generated by Django 4.2.16 on 2024-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0006_alter_externalmedia_options_alter_missionary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
