# Generated by Django 4.2.16 on 2024-11-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0007_alter_tag_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='description',
            new_name='tag_description',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='is_predefined',
            new_name='tag_is_predefined',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
