# Generated by Django 4.2.16 on 2025-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0009_profile_remove_supporter_user_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='BaseApp.tag'),
        ),
    ]
